version: "3.8"

services:
  devcontainer:
    build:
      dockerfile: .devcontainer/dev.dockerfile
      context: ../
    volumes:
      - ../:/workspace
      - poetry_cache:/home/vscode/.cache/pypoetry
  

volumes:
  poetry_cache:
    external: true